export const DRUG_SYNONYMS: Record<string, string[]> = {
  paracetamol: ["acetaminophen"],
  panadol: ["acetaminophen"],
  calpol: ["acetaminophen"],
  taylol: ["acetaminophen"],
  brufen: ["ibuprofen"],
  ibrufen: ["ibuprofen"],
  nurofen: ["ibuprofen"],
  advil: ["ibuprofen"],
  voltaren: ["diclofenac"],
  amoxil: ["amoxicillin"],
  augmentin: ["amoxicillin", "clavulanate"],
  "co-amoxiclav": ["amoxicillin", "clavulanate"],
  "co-trimoxazole": ["sulfamethoxazole", "trimethoprim"],
  cotrimoxazole: ["sulfamethoxazole", "trimethoprim"],
  septrin: ["sulfamethoxazole", "trimethoprim"],
  bactrim: ["sulfamethoxazole", "trimethoprim"],
  ciproxin: ["ciprofloxacin"],
  cipro: ["ciprofloxacin"],
  flagyl: ["metronidazole"],
  zentel: ["albendazole"],
  vermox: ["mebendazole"],
  daktarin: ["miconazole"],
  piriton: ["chlorpheniramine"],
  losec: ["omeprazole"],
  ventolin: ["salbutamol", "albuterol"],
  glyburide: ["glibenclamide"],
  glibenclamide: ["glyburide"],
  frusemide: ["furosemide"],
  lignocaine: ["lidocaine"],
  pethidine: ["meperidine"],
  adrenaline: ["epinephrine"],
  noradrenaline: ["norepinephrine"],
  valium: ["diazepam"],
  coartem: ["artemether", "lumefantrine"],
  norvasc: ["amlodipine"],
  zovirax: ["acyclovir"],
  klaricid: ["clarithromycin"],
  erythrocin: ["erythromycin"],
  rocephin: ["ceftriaxone"],
  claforan: ["cefotaxime"],
  zinacef: ["cefuroxime"],
  fortecort: ["dexamethasone"],
  solucortef: ["hydrocortisone"],
  diclofenac: ["diclofenac"],
  cloxacillin: ["cloxacillin"],
  ceftriaxone: ["ceftriaxone"],
  artemether: ["artemether"],
  lumefantrine: ["lumefantrine"],
  quinine: ["quinine"],
  amlodipine: ["amlodipine"],
  nifedipine: ["nifedipine"],
  propranolol: ["propranolol"],
  atenolol: ["atenolol"],
  captopril: ["captopril"],
  enalapril: ["enalapril"],
  valsartan: ["valsartan"],
  losartan: ["losartan"],
  spironolactone: ["spironolactone"],
  furosemide: ["furosemide"],
  bendroflumethiazide: ["bendroflumethiazide"],
  indapamide: ["indapamide"],
  atorvastatin: ["atorvastatin"],
  simvastatin: ["simvastatin"],
  pravastatin: ["pravastatin"],
  rosuvastatin: ["rosuvastatin"],
  clopidogrel: ["clopidogrel"],
  warfarin: ["warfarin"],
  enoxaparin: ["enoxaparin"],
  heparin: ["heparin"],
  digoxin: ["digoxin"],
  amiodarone: ["amiodarone"],
  nitroglycerin: ["nitroglycerin"],
  isosorbide: ["isosorbide"],
  omeprazole: ["omeprazole"],
  esomeprazole: ["esomeprazole"],
  lansoprazole: ["lansoprazole"],
  pantoprazole: ["pantoprazole"],
  ranitidine: ["ranitidine"],
  ondansetron: ["ondansetron"],
  metoclopramide: ["metoclopramide"],
  domperidone: ["domperidone"],
  insulin: ["insulin"],
  metformin: ["metformin"],
  gliclazide: ["gliclazide"],
  pioglitazone: ["pioglitazone"],
  sitagliptin: ["sitagliptin"],
  levothyroxine: ["levothyroxine"],
  carbimazole: ["carbimazole"],
  prednisolone: ["prednisolone"],
  dexamethasone: ["dexamethasone"],
  betamethasone: ["betamethasone"],
  beclomethasone: ["beclomethasone"],
  salbutamol: ["salbutamol"],
  ipratropium: ["ipratropium"],
  theophylline: ["theophylline"],
  budesonide: ["budesonide"],
  montelukast: ["montelukast"],
  doxycycline: ["doxycycline"],
  tetracycline: ["tetracycline"],
  azithromycin: ["azithromycin"],
  clarithromycin: ["clarithromycin"],
  levofloxacin: ["levofloxacin"],
  cefalexin: ["cephalexin"],
  cephalexin: ["cephalexin"],
  flucloxacillin: ["flucloxacillin"],
  neomycin: ["neomycin"],
  gentamicin: ["gentamicin"],
  vancomycin: ["vancomycin"],
  clindamycin: ["clindamycin"],
  metronidazole: ["metronidazole"],
  aciclovir: ["acyclovir"],
  fluconazole: ["fluconazole"],
  ketoconazole: ["ketoconazole"],
  griseofulvin: ["griseofulvin"],
  albendazole: ["albendazole"],
  ivermectin: ["ivermectin"],
  praziquantel: ["praziquantel"],
  artesunate: ["artesunate"],
  chloroquine: ["chloroquine"],
  primaquine: ["primaquine"],
  vitamins: ["multivitamin"],
  calcium: ["calcium"],
  iron: ["ferrous"],
  folate: ["folic acid"],
  tramadol: ["tramadol"],
  morphine: ["morphine"],
  meperidine: ["meperidine"],
  buprenorphine: ["buprenorphine"],
  ibuprofen: ["ibuprofen"],
  naproxen: ["naproxen"],
  ketorolac: ["ketorolac"],
  indomethacin: ["indomethacin"],
  allopurinol: ["allopurinol"],
  colchicine: ["colchicine"],
  sulfasalazine: ["sulfasalazine"],
  azathioprine: ["azathioprine"],
  methotrexate: ["methotrexate"],
  diazepam: ["diazepam"],
  lorazepam: ["lorazepam"],
  clonazepam: ["clonazepam"],
  midazolam: ["midazolam"],
  phenytoin: ["phenytoin"],
  phenobarbital: ["phenobarbital"],
  carbamazepine: ["carbamazepine"],
  valproate: ["valproic acid"],
  topiramate: ["topiramate"],
  levetiracetam: ["levetiracetam"],
  haloperidol: ["haloperidol"],
  chlorpromazine: ["chlorpromazine"],
  risperidone: ["risperidone"],
  olanzapine: ["olanzapine"],
  fluoxetine: ["fluoxetine"],
  sertraline: ["sertraline"],
  amitriptyline: ["amitriptyline"],
  imipramine: ["imipramine"],
  lithium: ["lithium"],
  donepezil: ["donepezil"],
  levodopa: ["levodopa"],
  carbidopa: ["carbidopa"],
  benzatropine: ["benztropine"],
  tamsulosin: ["tamsulosin"],
  finasteride: ["finasteride"],
  sildenafil: ["sildenafil"],
  salicylic: ["salicylic acid"],
  clotrimazole: ["clotrimazole"],
  miconazole: ["miconazole"],
  terbinafine: ["terbinafine"],
  silvadene: ["silver sulfadiazine"],
  bacitracin: ["bacitracin"],
  chlorhexidine: ["chlorhexidine"],
  povidone: ["povidone-iodine"],
};

export const SYNC_UNIT_TOKENS = new Set([
  "tablet", "tablets", "tab", "tabs", "cap", "caps", "capsule", "capsules",
  "syrup", "suspension", "susp", "drops", "mixture", "elixir",
  "injection", "inj", "infusion", "iv", "im", "sc", "po", "oral", "topical",
  "ointment", "cream", "gel", "lotion", "solution", "spray", "suppository",
  "mg", "mcg", "microgram", "micrograms", "ml", "g", "gm", "gram", "grams",
  "iu", "units", "u", "%", "pct", "strength",
]);

export function cleanDrugQuery(raw: string): string {
  return raw.toLowerCase().replace(/[^\w\s.+%/-]/g, " ").replace(/\s+/g, " ").trim();
}

export function searchCandidates(q: string): string[] {
  const tokens = q
    .toLowerCase()
    .replace(/[^\w\s.-]/g, " ")
    .split(/\s+/)
    .filter(Boolean)
    .filter((t) => !SYNC_UNIT_TOKENS.has(t) && !/^\d+$/.test(t));

  if (tokens.length === 0) return [];

  const cleaned = tokens.join(" ");
  const candidates: string[] = [];
  if (cleaned) candidates.push(cleaned);
  if (tokens.length > 1) candidates.push(tokens[0]);

  const expanded: string[] = [];
  for (const c of candidates) {
    const mapped = DRUG_SYNONYMS[c];
    if (mapped) {
      for (const m of mapped) if (!expanded.includes(m)) expanded.push(m);
      continue;
    }
    if (!expanded.includes(c)) expanded.push(c);
    const base = c.replaceAll("-", " ");
    if (base !== c && !expanded.includes(base)) expanded.push(base);
  }
  return expanded;
}