export type Row = Record<string, unknown>;
export type Db = Record<string, Row[]>;

function iso(offsetDays: number, hours = 8, minutes = 0): string {
  const d = new Date();
  d.setDate(d.getDate() + offsetDays);
  d.setHours(hours, minutes, 0, 0);
  return d.toISOString();
}

function dateStr(offsetDays: number): string {
  const d = new Date();
  d.setDate(d.getDate() + offsetDays);
  return d.toISOString().slice(0, 10);
}

function clone<T>(value: T): T {
  return JSON.parse(JSON.stringify(value)) as T;
}

export function buildDb(): Db {
  const todayIdx = (new Date().getDay() + 6) % 7;
  const mondayOffset = -todayIdx;

  return {
    settings: [
      { id: "set-1", key: "institution_name", value: "Muhimbili University of Health Sciences" },
      { id: "set-2", key: "academic_year", value: "2025/2026" },
    ],

    programs: [
      {
        id: "prog-mbbs",
        name: "Bachelor of Medicine and Bachelor of Surgery",
        code: "MBBS",
        duration_years: 5,
        description: "Comprehensive medical degree programme",
        created_at: iso(-900),
      },
      {
        id: "prog-bds",
        name: "Bachelor of Dental Surgery",
        code: "BDS",
        duration_years: 5,
        description: "Dental surgery programme",
        created_at: iso(-900),
      },
      {
        id: "prog-nursing",
        name: "Bachelor of Science in Nursing",
        code: "BScN",
        duration_years: 4,
        description: "Nursing programme",
        created_at: iso(-900),
      },
      {
        id: "prog-pharm",
        name: "Bachelor of Pharmacy",
        code: "BPharm",
        duration_years: 4,
        description: "Pharmacy programme",
        created_at: iso(-900),
      },
      {
        id: "prog-bmls",
        name: "Bachelor of Science in Medical Laboratory Sciences",
        code: "BMLS",
        duration_years: 4,
        description: "Medical laboratory sciences programme",
        created_at: iso(-900),
      },
      {
        id: "prog-bsc-clinical-medicine",
        name: "Bachelor of Science in Clinical Medicine",
        code: "BSc Clin Med",
        duration_years: 4,
        description: "Clinical medicine programme",
        created_at: iso(-900),
      },
      {
        id: "prog-bsc-physiotherapy",
        name: "Bachelor of Science in Physiotherapy",
        code: "BSc Physio",
        duration_years: 4,
        description: "Physiotherapy programme",
        created_at: iso(-900),
      },
      {
        id: "prog-bsc-environmental-health",
        name: "Bachelor of Science in Environmental Health Sciences",
        code: "BSc Env Health",
        duration_years: 4,
        description: "Environmental health programme",
        created_at: iso(-900),
      },
      {
        id: "prog-bsc-nutrition",
        name: "Bachelor of Science in Nutrition and Dietetics",
        code: "BSc Nutrition",
        duration_years: 4,
        description: "Nutrition and dietetics programme",
        created_at: iso(-900),
      },
      {
        id: "prog-dip-clinical-medicine",
        name: "Diploma in Clinical Medicine",
        code: "Dip Clin Med",
        duration_years: 3,
        description: "Clinical medicine diploma",
        created_at: iso(-900),
      },
      {
        id: "prog-dip-nursing-midwifery",
        name: "Diploma in Nursing and Midwifery",
        code: "Dip Nursing",
        duration_years: 3,
        description: "Nursing and midwifery diploma",
        created_at: iso(-900),
      },
      {
        id: "prog-dip-pharmaceutical",
        name: "Diploma in Pharmaceutical Sciences",
        code: "Dip Pharmacy",
        duration_years: 3,
        description: "Pharmaceutical sciences diploma",
        created_at: iso(-900),
      },
      {
        id: "prog-dip-medical-lab",
        name: "Diploma in Medical Laboratory Sciences",
        code: "Dip Med Lab",
        duration_years: 3,
        description: "Medical laboratory diploma",
        created_at: iso(-900),
      },
      {
        id: "prog-dip-radiography",
        name: "Diploma in Radiography",
        code: "Dip Radiography",
        duration_years: 3,
        description: "Radiography diploma",
        created_at: iso(-900),
      },
      {
        id: "prog-dip-physiotherapy",
        name: "Diploma in Physiotherapy",
        code: "Dip Physio",
        duration_years: 3,
        description: "Physiotherapy diploma",
        created_at: iso(-900),
      },
      {
        id: "prog-dip-environmental-health",
        name: "Diploma in Environmental Health Sciences",
        code: "Dip Env Health",
        duration_years: 3,
        description: "Environmental health diploma",
        created_at: iso(-900),
      },
      {
        id: "prog-dip-nutrition",
        name: "Diploma in Nutrition",
        code: "Dip Nutrition",
        duration_years: 3,
        description: "Nutrition diploma",
        created_at: iso(-900),
      },
      {
        id: "prog-dip-dental-therapy",
        name: "Diploma in Dental Therapy",
        code: "Dip Dental",
        duration_years: 3,
        description: "Dental therapy diploma",
        created_at: iso(-900),
      },
      {
        id: "prog-dip-health-records",
        name: "Diploma in Health Records and Information Technology",
        code: "Dip Health Rec",
        duration_years: 3,
        description: "Health records diploma",
        created_at: iso(-900),
      },
      {
        id: "prog-dip-public-health",
        name: "Diploma in Public Health",
        code: "Dip Public Health",
        duration_years: 3,
        description: "Public health diploma",
        created_at: iso(-900),
      },
      {
        id: "prog-cert-nursing",
        name: "Certificate in Nursing and Midwifery",
        code: "Cert Nursing",
        duration_years: 2,
        description: "Nursing and midwifery certificate",
        created_at: iso(-900),
      },
      {
        id: "prog-cert-clinical-medicine",
        name: "Certificate in Clinical Medicine",
        code: "Cert Clin Med",
        duration_years: 2,
        description: "Clinical medicine certificate",
        created_at: iso(-900),
      },
      {
        id: "prog-cert-pharmaceutical",
        name: "Certificate in Pharmaceutical Sciences",
        code: "Cert Pharmacy",
        duration_years: 2,
        description: "Pharmaceutical sciences certificate",
        created_at: iso(-900),
      },
      {
        id: "prog-cert-medical-lab",
        name: "Certificate in Medical Laboratory Sciences",
        code: "Cert Med Lab",
        duration_years: 2,
        description: "Medical laboratory certificate",
        created_at: iso(-900),
      },
      {
        id: "prog-cert-environmental-health",
        name: "Certificate in Environmental Health Sciences",
        code: "Cert Env Health",
        duration_years: 2,
        description: "Environmental health certificate",
        created_at: iso(-900),
      },
      {
        id: "prog-cert-nutrition",
        name: "Certificate in Nutrition",
        code: "Cert Nutrition",
        duration_years: 2,
        description: "Nutrition certificate",
        created_at: iso(-900),
      },
      {
        id: "prog-cert-health-records",
        name: "Certificate in Health Records",
        code: "Cert Health Rec",
        duration_years: 2,
        description: "Health records certificate",
        created_at: iso(-900),
      },
    ],

    courses: [
      { id: "c-anat101", name: "Anatomy", code: "ANAT 101", program_id: "prog-mbbs", semester: 1, credits: 6, description: "Gross and microscopic anatomy", created_at: iso(-850) },
      { id: "c-phys101", name: "Physiology", code: "PHYS 101", program_id: "prog-mbbs", semester: 1, credits: 5, description: "Human body function", created_at: iso(-850) },
      { id: "c-bioc101", name: "Biochemistry", code: "BIOC 101", program_id: "prog-mbbs", semester: 2, credits: 4, description: "Molecular basis of life", created_at: iso(-850) },
      { id: "c-pharm201", name: "Pharmacology", code: "PHARM 201", program_id: "prog-mbbs", semester: 3, credits: 5, description: "Drug action and therapy", created_at: iso(-800) },
      { id: "c-path201", name: "Pathology", code: "PATH 201", program_id: "prog-mbbs", semester: 3, credits: 5, description: "Mechanisms of disease", created_at: iso(-800) },
      { id: "c-micr201", name: "Microbiology", code: "MICR 201", program_id: "prog-mbbs", semester: 4, credits: 4, description: "Infectious agents", created_at: iso(-800) },
      { id: "c-med301", name: "Internal Medicine", code: "MED 301", program_id: "prog-mbbs", semester: 5, credits: 8, description: "Adult medicine clinical clerkship", created_at: iso(-700) },
      { id: "c-surg301", name: "Surgery", code: "SURG 301", program_id: "prog-mbbs", semester: 5, credits: 8, description: "Surgical diseases and principles", created_at: iso(-700) },
      { id: "c-ped301", name: "Pediatrics", code: "PED 301", program_id: "prog-mbbs", semester: 6, credits: 6, description: "Child health", created_at: iso(-700) },
      { id: "c-obg301", name: "Obstetrics & Gynaecology", code: "OBG 301", program_id: "prog-mbbs", semester: 6, credits: 6, description: "Women's health and childbirth", created_at: iso(-700) },
    ],

    profiles: [
      {
        id: "adm-demo",
        role: "admin",
        full_name: "Dr. Baraka Mushi",
        email: "admin@med.local",
        phone: "+255 713 222 111",
        avatar_url: null,
        reg_no: null,
        program_id: null,
        year_of_study: null,
        gender: "male",
        dob: "1980-02-11",
        address: "Dar es Salaam, Tanzania",
        created_at: iso(-900),
      },
      {
        id: "stu-demo",
        role: "student",
        full_name: "Amina Juma",
        email: "student@med.local",
        phone: "+255 712 345 678",
        avatar_url: null,
        reg_no: "MED/2022/0147",
        program_id: "prog-mbbs",
        year_of_study: 4,
        gender: "female",
        dob: "2002-04-18",
        address: "Dar es Salaam, Tanzania",
        created_at: iso(-900),
      },
      {
        id: "stu-2",
        role: "student",
        full_name: "Kelvin Mwakasege",
        email: "kelvin.mwakasege@med.local",
        phone: "+255 755 123 456",
        avatar_url: null,
        reg_no: "MED/2022/0102",
        program_id: "prog-mbbs",
        year_of_study: 4,
        gender: "male",
        dob: "2001-09-03",
        address: "Morogoro, Tanzania",
        created_at: iso(-899),
      },
      {
        id: "stu-3",
        role: "student",
        full_name: "Zainabu Hassan",
        email: "zainabu.hassan@med.local",
        phone: "+255 762 555 444",
        avatar_url: null,
        reg_no: "MED/2022/0188",
        program_id: "prog-mbbs",
        year_of_study: 4,
        gender: "female",
        dob: "2002-01-27",
        address: "Dodoma, Tanzania",
        created_at: iso(-898),
      },
      {
        id: "stu-4",
        role: "student",
        full_name: "David Mushi",
        email: "david.mushi@med.local",
        phone: "+255 717 888 999",
        avatar_url: null,
        reg_no: "MED/2022/0056",
        program_id: "prog-mbbs",
        year_of_study: 4,
        gender: "male",
        dob: "2001-12-12",
        address: "Arusha, Tanzania",
        created_at: iso(-897),
      },
    ],

    exams: [
      { id: "ex-1", title: "Anatomy - Head & Neck", type: "exam", course_id: "c-anat101", program_id: "prog-mbbs", date: dateStr(-40), max_score: 100, created_by: "adm-demo", created_at: iso(-45) },
      { id: "ex-2", title: "Physiology - CVS", type: "exam", course_id: "c-phys101", program_id: "prog-mbbs", date: dateStr(-30), max_score: 100, created_by: "adm-demo", created_at: iso(-35) },
      { id: "ex-3", title: "Pharmacology - Antibiotics", type: "exam", course_id: "c-pharm201", program_id: "prog-mbbs", date: dateStr(-18), max_score: 100, created_by: "adm-demo", created_at: iso(-22) },
      { id: "ex-4", title: "Pathology - Inflammation", type: "exam", course_id: "c-path201", program_id: "prog-mbbs", date: dateStr(-9), max_score: 100, created_by: "adm-demo", created_at: iso(-12) },
      { id: "ex-5", title: "Microbiology - Parasitology", type: "exam", course_id: "c-micr201", program_id: "prog-mbbs", date: dateStr(-4), max_score: 100, created_by: "adm-demo", created_at: iso(-6) },
      { id: "ex-6", title: "Internal Medicine - Case Vignettes", type: "exam", course_id: "c-med301", program_id: "prog-mbbs", date: dateStr(2), max_score: 100, created_by: "adm-demo", created_at: iso(-1) },
      { id: "ex-7", title: "Surgery - Wound Care", type: "quiz", course_id: "c-surg301", program_id: "prog-mbbs", date: dateStr(6), max_score: 50, created_by: "adm-demo", created_at: iso(-2) },
      { id: "ex-8", title: "Biochemistry - Enzymology", type: "assignment", course_id: "c-bioc101", program_id: "prog-mbbs", date: dateStr(-60), max_score: 50, created_by: "adm-demo", created_at: iso(-65) },
      { id: "ex-9", title: "Pediatrics - Growth & Development", type: "exam", course_id: "c-ped301", program_id: "prog-mbbs", date: dateStr(12), max_score: 100, created_by: "adm-demo", created_at: iso(-3) },
    ],

    results: [
      { id: "res-1", student_id: "stu-demo", exam_id: "ex-1", score: 82, grade: "B+", remarks: "Good anatomical knowledge", published: true, created_at: iso(-39) },
      { id: "res-2", student_id: "stu-demo", exam_id: "ex-2", score: 75, grade: "B", remarks: null, published: true, created_at: iso(-29) },
      { id: "res-3", student_id: "stu-demo", exam_id: "ex-3", score: 91, grade: "A", remarks: "Excellent", published: true, created_at: iso(-17) },
      { id: "res-4", student_id: "stu-demo", exam_id: "ex-4", score: 68, grade: "B-", remarks: "Revise chronic inflammation", published: true, created_at: iso(-8) },
      { id: "res-5", student_id: "stu-demo", exam_id: "ex-5", score: 84, grade: "B+", remarks: null, published: true, created_at: iso(-3) },
      { id: "res-6", student_id: "stu-demo", exam_id: "ex-8", score: 79, grade: "B+", remarks: null, published: true, created_at: iso(-59) },
      { id: "res-7", student_id: "stu-2", exam_id: "ex-1", score: 74, grade: "B", remarks: null, published: true, created_at: iso(-39) },
      { id: "res-8", student_id: "stu-2", exam_id: "ex-3", score: 88, grade: "A", remarks: null, published: true, created_at: iso(-17) },
      { id: "res-9", student_id: "stu-3", exam_id: "ex-1", score: 69, grade: "B-", remarks: null, published: true, created_at: iso(-39) },
      { id: "res-10", student_id: "stu-3", exam_id: "ex-3", score: 71, grade: "B", remarks: null, published: true, created_at: iso(-17) },
      { id: "res-11", student_id: "stu-4", exam_id: "ex-1", score: 55, grade: "C+", remarks: "Needs improvement", published: true, created_at: iso(-39) },
    ],

    timetable_entries: [
      { id: "tt-1", course_id: "c-med301", title: "Ward Rounds - Medical Wards", day_of_week: (mondayOffset + 0 + 7) % 7, start_time: "08:00", end_time: "10:00", location: "Medical Ward 3", teacher: "Dr. Mushi", type: "rotation", program_id: "prog-mbbs", created_at: iso(-120) },
      { id: "tt-2", course_id: "c-pharm201", title: "Antimicrobial Stewardship Lecture", day_of_week: (mondayOffset + 0 + 7) % 7, start_time: "11:00", end_time: "12:30", location: "Lecture Hall B", teacher: "Dr. Kileo", type: "lecture", program_id: "prog-mbbs", created_at: iso(-120) },
      { id: "tt-3", course_id: "c-surg301", title: "Surgical Skills Lab", day_of_week: (mondayOffset + 1 + 7) % 7, start_time: "09:00", end_time: "11:00", location: "Skills Lab 2", teacher: "Prof. Mteta", type: "practical", program_id: "prog-mbbs", created_at: iso(-120) },
      { id: "tt-4", course_id: "c-med301", title: "Grand Rounds", day_of_week: (mondayOffset + 2 + 7) % 7, start_time: "08:30", end_time: "10:00", location: "Main Conference Room", teacher: "Dr. Mushi", type: "seminar", program_id: "prog-mbbs", created_at: iso(-120) },
      { id: "tt-5", course_id: "c-path201", title: "Pathology Case Conference", day_of_week: (mondayOffset + 2 + 7) % 7, start_time: "14:00", end_time: "15:30", location: "Pathology Dept", teacher: "Dr. Lyimo", type: "seminar", program_id: "prog-mbbs", created_at: iso(-120) },
      { id: "tt-6", course_id: "c-ped301", title: "Pediatrics Ward Postings", day_of_week: (mondayOffset + 3 + 7) % 7, start_time: "08:00", end_time: "12:00", location: "Pediatrics Ward", teacher: "Dr. Ngowi", type: "rotation", program_id: "prog-mbbs", created_at: iso(-120) },
      { id: "tt-7", course_id: "c-micr201", title: "Microbiology Practical", day_of_week: (mondayOffset + 3 + 7) % 7, start_time: "13:00", end_time: "15:00", location: "Lab 1", teacher: "Dr. Kilonzo", type: "practical", program_id: "prog-mbbs", created_at: iso(-120) },
      { id: "tt-8", course_id: "c-obg301", title: "Obstetrics Clinic", day_of_week: (mondayOffset + 4 + 7) % 7, start_time: "09:00", end_time: "12:00", location: "ANC Clinic", teacher: "Dr. Sanga", type: "rotation", program_id: "prog-mbbs", created_at: iso(-120) },
      { id: "tt-9", course_id: "c-bioc101", title: "Biochemistry Tutorial", day_of_week: (mondayOffset + 4 + 7) % 7, start_time: "14:00", end_time: "15:00", location: "Room 7", teacher: "Dr. Mshana", type: "lecture", program_id: "prog-mbbs", created_at: iso(-120) },
    ],

    attendance: [
      { id: "at-1", student_id: "stu-demo", course_id: "c-med301", date: dateStr(-6), status: "present", lecturer: "Dr. Mushi", note: null, created_at: iso(-6) },
      { id: "at-2", student_id: "stu-demo", course_id: "c-surg301", date: dateStr(-5), status: "present", lecturer: "Prof. Mteta", note: null, created_at: iso(-5) },
      { id: "at-3", student_id: "stu-demo", course_id: "c-med301", date: dateStr(-4), status: "late", lecturer: "Dr. Mushi", note: "Traffic", created_at: iso(-4) },
      { id: "at-4", student_id: "stu-demo", course_id: "c-path201", date: dateStr(-3), status: "present", lecturer: "Dr. Lyimo", note: null, created_at: iso(-3) },
      { id: "at-5", student_id: "stu-demo", course_id: "c-ped301", date: dateStr(-2), status: "present", lecturer: "Dr. Ngowi", note: null, created_at: iso(-2) },
      { id: "at-6", student_id: "stu-demo", course_id: "c-micr201", date: dateStr(-1), status: "present", lecturer: "Dr. Kilonzo", note: null, created_at: iso(-1) },
      { id: "at-7", student_id: "stu-demo", course_id: "c-obg301", date: dateStr(0), status: "present", lecturer: "Dr. Sanga", note: null, created_at: iso(0) },
      { id: "at-8", student_id: "stu-demo", course_id: "c-bioc101", date: dateStr(-10), status: "absent", lecturer: "Dr. Mshana", note: "Sick", created_at: iso(-10) },
      { id: "at-9", student_id: "stu-demo", course_id: "c-pharm201", date: dateStr(-12), status: "present", lecturer: "Dr. Kileo", note: null, created_at: iso(-12) },
      { id: "at-10", student_id: "stu-demo", course_id: "c-anat101", date: dateStr(-15), status: "present", lecturer: "Dr. Ndosi", note: null, created_at: iso(-15) },
      { id: "at-11", student_id: "stu-demo", course_id: "c-phys101", date: dateStr(-20), status: "present", lecturer: "Dr. Kalokola", note: null, created_at: iso(-20) },
      { id: "at-12", student_id: "stu-2", course_id: "c-med301", date: dateStr(0), status: "present", lecturer: "Dr. Mushi", note: null, created_at: iso(0) },
      { id: "at-13", student_id: "stu-2", course_id: "c-med301", date: dateStr(-1), status: "present", lecturer: "Dr. Mushi", note: null, created_at: iso(-1) },
      { id: "at-14", student_id: "stu-3", course_id: "c-med301", date: dateStr(0), status: "late", lecturer: "Dr. Mushi", note: null, created_at: iso(0) },
      { id: "at-15", student_id: "stu-4", course_id: "c-med301", date: dateStr(0), status: "absent", lecturer: "Dr. Mushi", note: null, created_at: iso(0) },
      { id: "at-16", student_id: "stu-2", course_id: "c-surg301", date: dateStr(-5), status: "present", lecturer: "Prof. Mteta", note: null, created_at: iso(-5) },
      { id: "at-17", student_id: "stu-3", course_id: "c-surg301", date: dateStr(-5), status: "present", lecturer: "Prof. Mteta", note: null, created_at: iso(-5) },
    ],

    clinical_rotations: [
      {
        id: "rot-1",
        student_id: "stu-demo",
        department: "Internal Medicine",
        hospital: "Muhimbili National Hospital",
        start_date: dateStr(-30),
        end_date: dateStr(35),
        supervisor: "Dr. Mushi",
        hours_required: 120,
        status: "active",
        created_at: iso(-35),
      },
      {
        id: "rot-2",
        student_id: "stu-demo",
        department: "Surgery",
        hospital: "Muhimbili National Hospital",
        start_date: dateStr(-95),
        end_date: dateStr(-31),
        supervisor: "Prof. Mteta",
        hours_required: 100,
        status: "completed",
        created_at: iso(-100),
      },
      {
        id: "rot-3",
        student_id: "stu-demo",
        department: "Pediatrics",
        hospital: "Bugando Medical Centre",
        start_date: dateStr(40),
        end_date: dateStr(105),
        supervisor: "Dr. Ngowi",
        hours_required: 90,
        status: "upcoming",
        created_at: iso(-10),
      },
      {
        id: "rot-4",
        student_id: "stu-2",
        department: "Internal Medicine",
        hospital: "Muhimbili National Hospital",
        start_date: dateStr(-30),
        end_date: dateStr(35),
        supervisor: "Dr. Mushi",
        hours_required: 120,
        status: "active",
        created_at: iso(-35),
      },
      {
        id: "rot-5",
        student_id: "stu-3",
        department: "Internal Medicine",
        hospital: "Muhimbili National Hospital",
        start_date: dateStr(-30),
        end_date: dateStr(35),
        supervisor: "Dr. Mushi",
        hours_required: 120,
        status: "active",
        created_at: iso(-35),
      },
    ],

    rotation_hours: [
      { id: "rh-1", rotation_id: "rot-1", date: dateStr(-25), hours: 8, activity: "Ward rounds", note: null, created_at: iso(-25) },
      { id: "rh-2", rotation_id: "rot-1", date: dateStr(-20), hours: 6, activity: "Clinic attendance", note: null, created_at: iso(-20) },
      { id: "rh-3", rotation_id: "rot-1", date: dateStr(-15), hours: 8, activity: "Ward rounds", note: null, created_at: iso(-15) },
      { id: "rh-4", rotation_id: "rot-1", date: dateStr(-8), hours: 4, activity: "Case presentation", note: "Presented to team", created_at: iso(-8) },
      { id: "rh-5", rotation_id: "rot-1", date: dateStr(-2), hours: 8, activity: "Night shift", note: null, created_at: iso(-2) },
      { id: "rh-6", rotation_id: "rot-2", date: dateStr(-90), hours: 8, activity: "Ward rounds", note: null, created_at: iso(-90) },
      { id: "rh-7", rotation_id: "rot-2", date: dateStr(-80), hours: 7, activity: "OT observation", note: null, created_at: iso(-80) },
      { id: "rh-8", rotation_id: "rot-2", date: dateStr(-70), hours: 8, activity: "Ward rounds", note: null, created_at: iso(-70) },
      { id: "rh-9", rotation_id: "rot-2", date: dateStr(-60), hours: 6, activity: "Dressing clinic", note: null, created_at: iso(-60) },
      { id: "rh-10", rotation_id: "rot-2", date: dateStr(-50), hours: 8, activity: "Ward rounds", note: null, created_at: iso(-50) },
    ],

    case_logs: [
      {
        id: "cl-1",
        student_id: "stu-demo",
        date: dateStr(-28),
        department: "Internal Medicine",
        diagnosis: "Type 2 Diabetes Mellitus",
        procedure: null,
        patient_age: 54,
        patient_gender: "female",
        brief: "Assessed a 54-year-old female with polyuria and fatigue. Managed workup for hyperglycaemia.",
        reflection: "Learned about insulin vs oral hypoglycaemic escalation ladder.",
        supervisor_signoff: true,
        status: "approved",
        created_at: iso(-28),
      },
      {
        id: "cl-2",
        student_id: "stu-demo",
        date: dateStr(-18),
        department: "Internal Medicine",
        diagnosis: "Pneumonia",
        procedure: "IV cannulation",
        patient_age: 61,
        patient_gender: "male",
        brief: "Admitted patient with right lower lobe pneumonia, started on IV antibiotics.",
        reflection: "Practised chest auscultation findings of consolidation.",
        supervisor_signoff: true,
        status: "approved",
        created_at: iso(-18),
      },
      {
        id: "cl-3",
        student_id: "stu-demo",
        date: dateStr(-7),
        department: "Surgery",
        diagnosis: "Acute Appendicitis",
        procedure: "Assisted appendectomy",
        patient_age: 22,
        patient_gender: "female",
        brief: "Presented with RIF pain. Assisted in open appendectomy under supervision.",
        reflection: "Reviewed McBurney's point and surgical anatomy.",
        supervisor_signoff: false,
        status: "submitted",
        created_at: iso(-7),
      },
      {
        id: "cl-4",
        student_id: "stu-demo",
        date: dateStr(-1),
        department: "Internal Medicine",
        diagnosis: "Malaria",
        procedure: null,
        patient_age: 30,
        patient_gender: "male",
        brief: "Fever with rigors, positive blood film for P. falciparum. Started on AL.",
        reflection: null,
        supervisor_signoff: false,
        status: "draft",
        created_at: iso(-1),
      },
    ],

    study_materials: [
      { id: "mat-1", title: "Anatomy Lecture Notes - Upper Limb", type: "notes", course_id: "c-anat101", program_id: "prog-mbbs", uploaded_by: "adm-demo", file_url: null, description: "Comprehensive notes on brachial plexus", created_at: iso(-100) },
      { id: "mat-2", title: "CVS Physiology Slides", type: "slides", course_id: "c-phys101", program_id: "prog-mbbs", uploaded_by: "adm-demo", file_url: null, description: "Cardiac cycle and regulation", created_at: iso(-90) },
      { id: "mat-3", title: "Antibiotic Chart PDF", type: "pdf", course_id: "c-pharm201", program_id: "prog-mbbs", uploaded_by: "adm-demo", file_url: null, description: "Quick reference chart", created_at: iso(-80) },
      { id: "mat-4", title: "Pathology of Inflammation Video", type: "video", course_id: "c-path201", program_id: "prog-mbbs", uploaded_by: "adm-demo", file_url: null, description: "Lecture recording", created_at: iso(-70) },
      { id: "mat-5", title: "Parasitology Atlas Link", type: "link", course_id: "c-micr201", program_id: "prog-mbbs", uploaded_by: "adm-demo", file_url: null, description: "Online atlas", created_at: iso(-60) },
      { id: "mat-6", title: "Clinical Examination Guide", type: "pdf", course_id: "c-med301", program_id: "prog-mbbs", uploaded_by: "adm-demo", file_url: null, description: "OSCE preparation", created_at: iso(-30) },
    ],

    drugs: [
      { id: "dr-1", name: "Paracetamol", generic_name: "Acetaminophen", drug_class: "Analgesic / Antipyretic", indications: "Pain, fever", dosage: "500-1000mg every 4-6h (max 4g/day)", side_effects: "Hepatotoxicity in overdose", contraindications: "Severe liver disease", created_at: iso(-900) },
      { id: "dr-2", name: "Amoxicillin", generic_name: "Amoxicillin", drug_class: "Penicillin antibiotic", indications: "Bacterial infections (RTI, UTI)", dosage: "250-500mg every 8h", side_effects: "Rash, diarrhoea, allergy", contraindications: "Penicillin allergy", created_at: iso(-900) },
      { id: "dr-3", name: "Artemether/Lumefantrine", generic_name: "Co-artemether", drug_class: "Antimalarial", indications: "Uncomplicated P. falciparum malaria", dosage: "4 tablets twice daily x 3 days (weight-based)", side_effects: "Nausea, headache, palpitations", contraindications: "1st trimester (preferred alternatives)", created_at: iso(-900) },
      { id: "dr-4", name: "Metformin", generic_name: "Metformin HCl", drug_class: "Biguanide antidiabetic", indications: "Type 2 diabetes mellitus", dosage: "500mg twice daily, titrate to 2g/day", side_effects: "GI upset, B12 deficiency", contraindications: "Renal failure (eGFR<30), lactic acidosis", created_at: iso(-900) },
      { id: "dr-5", name: "Omeprazole", generic_name: "Omeprazole", drug_class: "Proton pump inhibitor", indications: "GERD, peptic ulcer, H. pylori eradication", dosage: "20mg once daily", side_effects: "Headache, diarrhoea, hypomagnesaemia", contraindications: "None major", created_at: iso(-900) },
      { id: "dr-6", name: "Ceftriaxone", generic_name: "Ceftriaxone", drug_class: "3rd-gen cephalosporin", indications: "Severe infections, meningitis, sepsis", dosage: "1-2g IV/IM once daily", side_effects: "Biliary sludging, rash, C. difficile", contraindications: "Cephalosporin allergy", created_at: iso(-900) },
      { id: "dr-7", name: "Oral Rehydration Salts", generic_name: "ORS", drug_class: "Electrolyte replacement", indications: "Dehydration (diarrhoea, cholera)", dosage: "Sachet in 1L clean water, ad lib", side_effects: "None significant", contraindications: "None (avoid if ileus)", created_at: iso(-900) },
    ],

    notices: [
      { id: "no-1", title: "Final Year OSCE Schedule Released", body: "The OSCE schedule for the upcoming block has been released. Check your individual time slots.", audience: "students", pinned: true, created_by: "adm-demo", created_at: iso(-3) },
      { id: "no-2", title: "Tuition Payment Deadline", body: "Reminder that the semester fee deadline is approaching. Late payments attract a penalty.", audience: "all", pinned: true, created_by: "adm-demo", created_at: iso(-6) },
      { id: "no-3", title: "New Antimicrobial Policy", body: "The updated hospital antimicrobial stewardship policy is now available in the library.", audience: "all", pinned: false, created_by: "adm-demo", created_at: iso(-9) },
      { id: "no-4", title: "Research Elective Applications", body: "Applications for international electives open next week. Submit via the registry.", audience: "students", pinned: false, created_by: "adm-demo", created_at: iso(-12) },
      { id: "no-5", title: "Faculty Development Workshop", body: "All clinical educators are invited to the bedside teaching workshop on Friday.", audience: "admin", pinned: false, created_by: "adm-demo", created_at: iso(-14) },
    ],

    reminders: [
      { id: "rm-1", student_id: "stu-demo", title: "Submit case log 3 for sign-off", due_date: dateStr(1), done: false, type: "rotation", created_at: iso(-2) },
      { id: "rm-2", student_id: "stu-demo", title: "Internal Medicine exam", due_date: dateStr(2), done: false, type: "exam", created_at: iso(-4) },
      { id: "rm-3", student_id: "stu-demo", title: "Surgery quiz revision", due_date: dateStr(6), done: false, type: "exam", created_at: iso(-5) },
      { id: "rm-4", student_id: "stu-demo", title: "Semester fees - second instalment", due_date: dateStr(14), done: false, type: "payment", created_at: iso(-7) },
      { id: "rm-5", student_id: "stu-demo", title: "Pathology seminar paper", due_date: dateStr(-3), done: true, type: "assignment", created_at: iso(-20) },
    ],

    payments: [
      { id: "pay-1", student_id: "stu-demo", fee_type: "Tuition Fee 2025/2026", amount: 2500000, paid_amount: 2500000, due_date: dateStr(-60), status: "paid", method: "Bank transfer", date_paid: dateStr(-70), receipt_no: "RCP-2026-0081", created_at: iso(-70) },
      { id: "pay-2", student_id: "stu-demo", fee_type: "Accommodation Fee", amount: 900000, paid_amount: 500000, due_date: dateStr(15), status: "partial", method: "Mobile money", date_paid: dateStr(-10), receipt_no: "RCP-2026-0122", created_at: iso(-10) },
      { id: "pay-3", student_id: "stu-demo", fee_type: "Library & Examination Fee", amount: 300000, paid_amount: 0, due_date: dateStr(20), status: "unpaid", method: null, date_paid: null, receipt_no: null, created_at: iso(-30) },
      { id: "pay-4", student_id: "stu-2", fee_type: "Tuition Fee 2025/2026", amount: 2500000, paid_amount: 2500000, due_date: dateStr(-60), status: "paid", method: "Bank transfer", date_paid: dateStr(-68), receipt_no: "RCP-2026-0080", created_at: iso(-68) },
      { id: "pay-5", student_id: "stu-3", fee_type: "Tuition Fee 2025/2026", amount: 2500000, paid_amount: 1500000, due_date: dateStr(-60), status: "partial", method: "Bank transfer", date_paid: dateStr(-50), receipt_no: "RCP-2026-0099", created_at: iso(-50) },
      { id: "pay-6", student_id: "stu-4", fee_type: "Tuition Fee 2025/2026", amount: 2500000, paid_amount: 2500000, due_date: dateStr(-60), status: "paid", method: "Bank transfer", date_paid: dateStr(-72), receipt_no: "RCP-2026-0075", created_at: iso(-72) },
    ],

    sms_messages: [
      { id: "sms-1", student_id: "stu-demo", phone: "+255712345678", message: "Your OSCE slot is confirmed for 09:00.", status: "sent", type: "result", sent_at: iso(-2), created_at: iso(-2) },
      { id: "sms-2", student_id: "stu-2", phone: "+255755123456", message: "Tuition payment reminder: deadline approaching.", status: "pending", type: "payment", sent_at: null, created_at: iso(-1) },
      { id: "sms-3", student_id: "stu-3", phone: "+255762555444", message: "Grand rounds moved to 08:30.", status: "sent", type: "notice", sent_at: iso(-3), created_at: iso(-3) },
    ],

    activity_log: [
      { id: "act-1", user_id: "adm-demo", user_name: "Dr. Baraka Mushi", action: "created", entity: "Notice 'Final Year OSCE Schedule Released'", details: null, created_at: iso(-3) },
      { id: "act-2", user_id: "adm-demo", user_name: "Dr. Baraka Mushi", action: "published", entity: "Results for Microbiology - Parasitology", details: null, created_at: iso(-3) },
      { id: "act-3", user_id: "adm-demo", user_name: "Dr. Baraka Mushi", action: "added", entity: "Student Kelvin Mwakasege", details: null, created_at: iso(-4) },
      { id: "act-4", user_id: "adm-demo", user_name: "Dr. Baraka Mushi", action: "recorded", entity: "Payment for stu-3", details: null, created_at: iso(-5) },
      { id: "act-5", user_id: "adm-demo", user_name: "Dr. Baraka Mushi", action: "created", entity: "Exam 'Internal Medicine - Case Vignettes'", details: null, created_at: iso(-6) },
      { id: "act-6", user_id: "adm-demo", user_name: "Dr. Baraka Mushi", action: "updated", entity: "Rotation for stu-demo", details: null, created_at: iso(-8) },
    ],
  };
}

export function buildMockDb(): Db {
  return clone(buildDb());
}
